.muikit_js_metadata <- function() {
deps_metadata <- list(`muikit` = structure(list(name = "muikit",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-button.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "muikit",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`muikit` = structure(list(name = "muikit",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-button.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "muikit",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`muikit` = structure(list(name = "muikit",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'muikit.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "muikit",
all_files = FALSE), class = "html_dependency"),
`muikit` = structure(list(name = "muikit",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'muikit.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "muikit",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
